### ISSUE TITLE
Can't make use of charmhelpers from layer-basic from within the metrics layer

### ISSUE THREAD

**Issue by mattyw** [CanonicalLtd/layer-metrics#4] opened 2017-03-23 13:40 UTC
We import the charm dir lib:
https://github.com/CanonicalLtd/layer-metrics/blob/master/hooks/collect-metrics#L5

But charmhelpers is installed in a venv which we don't have access to. We should be doing something like:
```
# Load modules from $CHARM_DIR/lib
import sys
sys.path.append('lib')

from charms.layer import basic
basic.bootstrap_charm_deps()
basic.init_config_states()
```

**Comment by cmars** [comment] 2017-03-23 13:44
Is anything broken in this hook? I don't understand what the problem is, exactly.

**Comment by cmars** [comment] 2017-03-23 14:19
Closing this for now; the command scripts will need to paste the above snippet to access charmhelpers anyway.

Longer term, we could improve collect-metrics integration with reactive, but that will need some design consideration.

**Closed as completed by cmars** 2017-03-23 14:19 UTC
